teacher/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'bee'
from django.conf.urls import include, url
from teacher.views import *
urlpatterns = [

    # reg
    url(r'^reg$', reg, name='reg'),
    url(r'^apiReg$', api_reg, name='api_reg'),

    # 老师列表
    url(r'^teacherList$', teacher_list, name='teacher_list'),
    url(r'^trainings/(?P<teacher_oid>[\w]{24})/$', trainings, name='trainings'),
    url(r'^trainingEditForm$', trainingEditForm, name='trainingEditForm'),
    url(r'^trainingEdit$', trainingEdit, name='trainingEdit'),
    url(r'^changePw$', changePw, name='changePw'),
    url(r'^pwForm$', pwForm, name='pwForm'),
    url(r'^checkOpenId$',checkOpenId,name="checkOpenId"),
    url(r'^api_getMessage$',api_getMessage,name="api_getMessage"),
    url(r'^api_readMessage$',api_readMessage,name="api_readMessage"),
    url(r'^message$',message,name="message"),
    url(r'^api_sendMessage$',api_sendMessage,name="api_sendMessage"),
    url(r'^api_push$',api_push,name="api_push"),
    url(r'^teacherQrcode$',teacherQrcode,name="teacherQrcode"),
    url(r'^api_headmasterAssess$',api_headmasterAssess,name="api_headmasterAssess"),
    url(r'^headmasterAssess$',headmasterAssess,name="headmasterAssess"),
    url(r'^headmasterAssesses$',headmasterAssesses,name="headmasterAssesses"),
    url(r'^questionnaire$',questionnaire,name="questionnaire"),
    url(r'^api_questionnaire$',api_questionnaire,name="api_questionnaire"),
    url(r'^questionnaireResult$',questionnaireResult,name="questionnaireResult"),
    url(r'^teacherAvail$',teacherAvail,name="teacherAvail"),
    url(r'^markStep$',markStep,name="markStep"),
    url(r'^api_markStep$',api_markStep,name="api_markStep"),
    url(r'^wxqrcodePic$',wxqrcodePic,name="wxqrcodePic"),
    url(r'^p20181111$',p20181111,name="p20181111"),
    url(r'^cityTeacherSteps$',cityTeacherSteps,name="cityTeacherSteps"),
    url(r'^api_editTarget$', api_editTarget,name='api_editTarget'),  # @UndefinedVariable
    url(r'^teacherSteps$',teacherSteps,name="teacherSteps"),
    url(r'^api_resetTestPassword$',api_resetTestPassword,name="api_resetTestPassword"),
    url(r'^testUser$',testUser,name="testUser"),
    url(r'^q2019$',q2019,name="q2019"),
    url(r'^api_q2019$',api_q2019,name="api_q2019"),
    url(r'^q2019Result$',q2019Result,name="q2019Result"),
    
]

teacher/forms.py
from django import forms

class PicForm(forms.Form):
    tid = forms.CharField(widget=forms.HiddenInput())
    picFile = forms.ImageField()

teacher/templates/cityTeacherSteps.html
{% extends "base.html" %}
{% block content %}
<div style="padding-top:10px;padding-bottom:3;">
<a href="{% url 'statistic:indexStat' %}"><返回</a>
</div>
<style>
.column{
  float:left;border-right: 0px solid; width:280px;text-align: center;
}

td{padding: 6px;white-space: nowrap;text-align: center;border:1px solid;}
table{margin: 10px 0 20px 0;}
input[type=text]{width:60px;margin:0 10px 0 10px;}
select{font-size:24px;}
button{margin:8px 0 6px 0;}
</style>

<div style="clear:both;">
<hr>
  <center>
  <h3>{{yearBegin|date:"Y"}}-{{yearEnd|date:"Y"}}年度 老师成长档案</h3>
  <table id="datatable">
    <thead>
    <tr>
      <th>校区</th>
      <th>老师</th>
      <th>棋力月赛</th>
      <th>对弈</th>
      <th>教材讲解</th>
      <th>成交练习</th>
      <th>学生在线做题</th>
      <th>读后感</th>
      <th>文章</th>
      <th>家长分享</th>
      <th>朋友圈</th>
      <th>学生成长档案</th>
      <th>班级群</th>
      <th>家长课堂</th>
      <th>集体活动</th>
      <th>主任分</th>
      <th>总分</th>
    </tr>
  </thead>
  <tbody>
    {%for s in steps%}
    <tr>
      <td>{{s.branch}}</td>
      <td>{{s.name}}</td>
      <td>{{s.s1|default:''}}</td>
      <td>{{s.s2|default:''}}</td>
      <td>{{s.s3|default:''}}</td>
      <td>{{s.s4|default:''}}</td>
      <td>{{s.s5|default:''}}</td>
      <td>{{s.s6|default:''}}</td>
      <td>{{s.s7|default:''}}</td>
      <td>{{s.s8|default:''}}</td>
      <td>{{s.s9|default:''}}</td>
      <td>{{s.s10|default:''}}</td>
      <td>{{s.s11|default:''}}</td>
      <td>{{s.s12|default:''}}</td>
      <td>{{s.s13|default:''}}</td>
      <td>{{s.s14|default:''}}</td>
      <td>{{s.all|default:''}}</td>
    </tr>
    {%endfor%}
  </tbody>
  </table>
</center>
</div>

{% endblock %}
{% block scripts %}
<script>
$('#datatable').DataTable({
  "paging":   false,
  "searching": false,
  "info":true,
  "language": {
        "lengthMenu": "每页显示 _MENU_ ",
        "zeroRecords": "空空如也",
        "sInfo":"从 _START_ 到 _END_， 共 _TOTAL_ 老师",
        "infoEmpty": "没有找到哦",
        "sSearch":"查询"
      }
})
</script>
{% endblock %}

teacher/templates/headmasterAssesses.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div style="padding-top:10px;padding-bottom:3;">
<a href="{%url 'statistic:indexStat'%}"><返回</a>
</div>
<div>
<div style="margin-left:20px;"><center><b>主任评分</b>
<select id="city">
  {%for c in cities%}
    <option value="{{c.id}}" {%if city == c.id|stringformat:'s'%} selected="selected" {%endif%}>{{c.cityName}}</option>
  {%endfor%}
</select>
<select id="assessCode">
  {%for key,value in ASSESS_CODE.items%}
    <option value="{{key}}">{{key}}</option>
  {%endfor%}
</select>
<button id="searchButton">查询</button>
</center>
</div>
<center>
<div id="table-container" style="width:100%;padding-bottom:40px;">
<div style="float:left;width:20%">
  {%if assesses%}
  评分回收数
  <table border="1" id="datatable">
    <thead>
    <tr>
      <th>校区</th><th>回收数</th>
    </tr>
  </thead>
  <tbody>
    {%for key,value in bcounts.items%}
    <tr><td>{{key}}</td><td>{{value}}</td></tr>
    {%endfor%}
  </tbody>
  </table>
  {%endif%}
</div>
<div style="float:right;width:80%">
    <table id="datatable" border="1">
    <thead>
        <tr style="background:#eeeeee;">

        <th style="padding:3px 10px 3px 10px;width:74px;">校区</th>
        <th style="padding:3px 10px 3px 10px;width:80px;">主任</th>
        <th style="padding:3px 10px 3px 10px;width:60px;" align="center">评分</th>
        <th style="padding:3px 10px 3px 10px;width:500px;" align="center">评语</th>
        <th style="padding:3px 10px 3px 10px;width:60px;" align="center">平均分</th>

        </tr>
</thead>
<tbody>
{%for a in assesses%}
<tr>

<td style="padding:0 0 0 10px;">{{a.branchName}}</td>
<td style="padding:0 0 0 10px;">{{a.assessObjectName}}</td>
<td style="padding:0 0 0 10px;">{{a.score}}</td>
<td style="padding:0 0 0 10px;">{{a.memo}}</td>
<td style="padding:0 0 0 10px;">{{a.averageScore}}</td>
</tr>
{%endfor%}
</tbody>
</table>
</div>
</div>

{% endblock %}
{% block scripts %}
    <script>
    $("#searchButton").click(function(){
    	if($("#assessCode").val()==''){
    	    alert("请选择考评代号")
    	    return
        }
        if($("#city").val()==''){
        	alert("请选择城市")
        	return
        }
    	var url = "{%url 'teacher:headmasterAssesses'%}?assessCode="+$("#assessCode").val()+"&city="+$("#city").val();
    	$("#searchButton").html("<font style='color:grey;'>查询中...</font>")
    	window.location.href=url;
    })


    $(document).ready(function() {
        $('#datatable').DataTable({
        	    	"paging":   false,
           	"searching": false,
        	    "info":false,

            "order": [[ 1, "desc" ]],
            buttons: [
                { extend: 'copy', text: '复制' },
                { extend: 'csv', text: '保存' },
                { extend: 'print', text: '打印' }
            ]
    	});

    });
    </script>
{% endblock %}

teacher/templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div style="cursor:pointer;color:#999999">
  <h3>
    <img src="/go_static/img/yhLogo.jpg" width="30" />
    <b>弈海CRM</b>
  </h3>
</div>
<center>
    {% if uf.errors %}
        <div class="alert alert-danger">
            <p>
                <strong>{{ uf.errors }}</strong>
            </p>
        </div>
    {% endif %}
    {% if  msg %}
        <div class="alert alert-danger">
            <p>
                <strong>{{ msg }}</strong>
            </p>
        </div>
    {% endif %}
    <form name="form1" id="form1" style="max-width:300px;" method="post" enctype="multipart/form-data" role="form">
        {% csrf_token %}
        {{ uf.as_p }}
        <input type="hidden" id="openId" name="openId" />
        <button type="submit" class="btn btn-primary" id="submit">登录</button>
    </form>
</center>
{% endblock %}
{% block scripts %}
    <script>
    var Request = new QueryString();
    var openId = Request['openId'];
    $("#openId").val(openId);
        $(function () {
            $('form').submit(function () {
                $('#submit').button('loading');
            })
        });

    </script>
{% endblock %}

teacher/templates/markStep.html
{% extends "base.html" %}
{% block content %}
<div style="padding-top:10px;padding-bottom:3;">
<a href="{% url 'teacher:teacher_list' %}"><返回</a>
&nbsp;
<a href="{% url 'teacher:teacherSteps' %}">浏览全部档案></a>
</div>
<style>
  body{padding:0;margin:0;}

  optgroup{font-size:20px;}
  .container{margin:0;}
.column{
  float:left;border-right: 0px solid; width:280px;text-align: left;
}

td{padding: 4px;white-space: nowrap;text-align: center;border:1px solid;}
table{margin: 10px 0 20px 0;}
#targetTable td{border-color:#ec8d12;}
input[type=text]{width:60px;margin:0 10px 0 10px;}
select{font-size:16px;}
button{margin:8px 0 6px 0;}
</style>

<div class="column" style="max-width:700px;min-width:540px;">
  <span style="font-weight:bold;padding-left:10px;color:red;">棋力目标</span>
  <table id="targetTable">
    <thead>
      <tr>
        <td></td>
        <td>开始日期</td>
        <td>起点</td>
        <td>季度目标</td>
        <td>半年目标</td>
        <td>一年目标</td>
      </tr>
    </thead>
    <tbody>
      {%for t in teachers%}
      <tr>
        <td>{{t.name}}</td>
        <td><input class="targetInput"  type="text" id="{{t.id}}-beginDate" value="{%if t.targetBeginDate%}{{t.targetBeginDate|date:'Y-m-d'}}{%endif%}" style="width:90px;"></td>
        <td><select class="targetInput"  id="{{t.id}}-beginLevel">
          <optgroup>
          <option value="">请选择</option>
          {%for key,value in GO_LEVEL.items%}
          <option value="{{key}}" {%if t.beginLevel == key%}selected="selected"{%endif%}>{{key}}</option>
          {%endfor%}
          </optgroup>
          </select></td>
        <td><select  class="targetInput" id="{{t.id}}-quarterTarget">
          <option value="">请选择</option>
          {%for key,value in GO_LEVEL.items%}
          <option value="{{key}}" {%if t.targetLevel1 == key%}selected="selected"{%endif%}>{{key}}</option>
          {%endfor%}
          </select></td>
        <td><select class="targetInput"  id="{{t.id}}-halfyearTarget">
          <option value="">请选择</option>
          {%for key,value in GO_LEVEL.items%}
          <option value="{{key}}" {%if t.targetLevel2 == key%}selected="selected"{%endif%}>{{key}}</option>
          {%endfor%}
          </select></td>
        <td><select class="targetInput"  id="{{t.id}}-yearTarget">
          <option value="">请选择</option>
          {%for key,value in GO_LEVEL.items%}
          <<option value="{{key}}" {%if t.targetLevel3 == key%}selected="selected"{%endif%}>{{key}}</option>
          {%endfor%}
          </select></td>
      </tr>
{%endfor%}
      <tr><td colspan="8"><button onclick="saveTarget()">保存目标</button></td></tr>
    </tbody>
  </table>
</div>


<div class="column" style="max-width:600px;min-width:400px;">

    周记录
  <select id="week-beginDate">
    {%for week in weeks%}
    <option value="{{week.begin}}">{{week.begin}}到{{week.end}}</option>
    {%endfor%}
  </select>

  <table>
    <tr>
      <td></td>
      <td>正课试讲<br>至少一次</td>
      <td>成交演练<br>至少一次</td>
      <td>班级群反馈<br>每周都有</td>
      <td>对弈<br>至少30盘</td>
      <td>棋力</td>
    </tr>
    {%for t in teachers%}
    <tr>
      <td>{{t.name}}</td>
      <td><input class="weekInput" id='{{t.id}}-正课试讲' type="checkbox" /></td>
      <td><input class="weekInput" id='{{t.id}}-成交演练' type="checkbox" /></td>
      <td><input class="weekInput" id='{{t.id}}-班级群反馈' type="checkbox" /></td>
      <td><input class="weekInput" id='{{t.id}}-对弈' type="checkbox" /></td>
      <td><select class="weekInput" id='{{t.id}}-棋力'>
        {%for key,value in GO_LEVEL.items%}
        <option value="{{key}}">{{key}}</option>
        {%endfor%}
        </select>
    </tr>
    {%endfor%}
    <tr><td colspan="6"><button class="stepButton"  id="week">保存周记录</button>
    </td></tr>
  </table>

</div>

<div class="column" style="max-width:300px;min-width:140px;">

    月记录
  <select id="month-beginDate">
    {%for month in months%}
    <option value="{{month}}">{{month}}</option>
    {%endfor%}
  </select>

  <table>
  <tr>
    <td></td>
    <td>棋力月赛分数</td>

    <td>朋友圈<br>至少4次</td>
  </tr>
  {%for t in teachers%}
  <tr>
    <td>{{t.name}}</td>
    <td><select  class="monthInput"  id="{{t.id}}-棋力月赛">
      <option value="0">0</option>
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
    </select>
    </td>

    <td><input class="monthInput" id='{{t.id}}-朋友圈' type="checkbox" /></td>
  </tr>
  {%endfor%}

  <tr><td colspan="4"><button class="stepButton"  id="month">保存月记录</button>
  </td></tr>
</table>

</div>

<div class="column" style="max-width:300px;min-width:200px;">

    季度记录

  <select id="month3-beginDate">
    {%for m3 in month3%}
    <option value="{{m3.begin}}">{{m3.begin}}到{{m3.end}}</option>
    {%endfor%}
  </select>

  <table>
  <tr>
    <td></td>
    <td>家长课堂次数</td>


  </tr>
  {%for t in teachers%}
  <tr>
    <td>{{t.name}}</td>

    <td><select class="month3Input" id="{{t.id}}-家长课堂" style="">
    <option value="0">0次</option>
    <option value="1">1次</option>
    <option value="2">2次</option>
    <option value="3">3次</option>
    <option value="4">4次及以上</option>
    </select>
    </td>
  </tr>
  {%endfor%}
  <tr><td colspan="2"><button class="stepButton"  id="month3">保存季度记录</button>
  </td></tr>
</table>

</div>

<div class="column"  style="max-width:300px;min-width:200px;">

    年度记录
  <select id="year-beginDate">
    {%for year in years%}
    <option value="{{year.begin}}">{{year.begin}}到{{year.end}}</option>
    {%endfor%}
  </select>

  <table>
  <tr>
    <td></td>
    <td>集体活动</td>
    <td>主任分</td>

  </tr>
  {%for t in teachers%}
  <tr>
    <td>{{t.name}}</td>
    <td><input class="yearInput" id="{{t.id}}-集体活动" type="text" />分
    </td>
    <td><input class="yearInput" id="{{t.id}}-主任分" type="text"/>分</td>
  </tr>
  {%endfor%}

  <tr><td colspan="4"><button class="stepButton" id="year">保存年度记录</button>
  </td></tr>
</table>

</div>

<div style="clear:both;">

</div>

{% endblock %}
{% block scripts %}
<script>
{%for step in searchWeekSteps%}
    {%if step.valid%}
      $("#{{step.teacherId}}-{{step.item}}").prop('checked', true);
    {%endif%}
    {%if step.item == '棋力'%}
      $("#{{step.teacherId}}-{{step.item}}").val('{{step.value}}')
    {%endif%}
{%endfor%}

{%for step in searchMonthSteps%}
  {%if step.item == '棋力月赛'%}
  $("#{{step.teacherId}}-{{step.item}}").val('{{step.value}}')
  {%endif%}
  {%if step.item == '对弈' and step.valid%}
  $("#{{step.teacherId}}-{{step.item}}").prop('checked', true);
  {%endif%}
  {%if step.item == '朋友圈' and step.valid%}
  $("#{{step.teacherId}}-{{step.item}}").prop('checked', true);
  {%endif%}
{%endfor%}

{%for step in month3Steps%}
  $("#{{step.teacherId}}-{{step.item}}").val('{{step.value}}')
{%endfor%}

{%for step in yearSteps%}
  $("#{{step.teacherId}}-{{step.item}}").val('{{step.value}}')
{%endfor%}

$(".stepButton").click(function(){
  var items = ''
    var dateType = $(this).attr("id")
    $("."+dateType+"Input").each(function(){
      var tags = $(this).attr("id").split("-")
      items = items + tags[0] + '-' + tags[1]
      var value = ''
      var valid = ''
      var score = 0
      if($(this).attr("type")=='checkbox'){
        if($(this).prop("checked"))
          valid = 'true'
      }
      else if($(this).attr("type")=='text'){
        value = $(this).val()
      }
      else{
        value = $(this).val()
      }

      items = items + '-' + value + '-' + valid + '-' + score + '|'
    })
    console.log(items)
    items = items.substring(0,items.length-1)
    var beginDate = $("#"+dateType+"-beginDate").val()
    //return
		$.post("{% url 'teacher:api_markStep' %}", {
      "csrfmiddlewaretoken": "{{ csrf_token }}",
        	"branchId":'{{login_teacher.branch}}',
          "beginDateStr":beginDate,
          "dateType":dateType,
          "itemStr":items
        }, function (res) {

          alert(res.msg)
          location.reload();
        });

});
$("#week-beginDate").change(function(){
  var week = $(this).val()
  var url = "{% url 'teacher:markStep' %}?week="+week+"&month={{searchMonthBegin|date:"Y-m"}}";
  window.location.href=url;
})

$("#month-beginDate").change(function(){
  var month = $(this).val()
  var url = "{% url 'teacher:markStep' %}?month="+month+"&week={{searchWeekBegin|date:"Y-m-d"}}";
  window.location.href=url;
})
{%if searchWeekBegin%}
$("#week-beginDate").val('{{searchWeekBegin|date:"Y-m-d"}}')
{%endif%}

{%if searchMonthBegin%}
$("#month-beginDate").val('{{searchMonthBegin|date:"Y-m"}}')
{%endif%}

$('#beginDate').datetimepicker({
    timepicker: false,
    format: 'Y-m-d'
});


function saveTarget(){
  var items = ''

    $(".targetInput").each(function(){
      var tags = $(this).attr("id").split("-")
      items = items + tags[0] + '_' + tags[1]
      var value = ''
      value = $(this).val()
      items = items + '_' + value + '|'
    })
    console.log(items)
    items = items.substring(0,items.length-1)


  $.post("{% url 'teacher:api_editTarget' %}", {
      "items": items
  }, function (res) {
      if (res["error"] == 0) {
          alert("成功")
          window.location.reload();
      } else {
          alert("失败:" + res["msg"])
      }
  });
}
$('input.targetInput').datetimepicker({
    timepicker: false,
    format: 'Y-m-d'
});
</script>
{% endblock %}

teacher/templates/q2019.html
{% extends "base.html" %}
{% block content %}
	<style>
	body{font-family:微软雅黑,Arial;max-width:800px;margin:0 auto}
	h3{margin-top:5px;margin-bottom:5px;}
	h5{font-weight: bold;}
	div{padding:5px 0px 0px 5px;}
	#submitBtn{padding:10px 40px 10px 40px;font-size:16px;}
    label.valid {
	  width: 24px;
	  height: 24px;
	  background: url(assets/img/valid.png) center center no-repeat;
	  display: inline-block;
	  text-indent: -9999px;
    }
    label.error {
	  font-weight: bold;
	  color: red;
	  padding: 2px 8px;
	  margin-top: 2px;
    }
	</style>


<div style="width:100%;margin:0 auto;padding:0;">
<form id="qform" action="api_q2019" method="post" class="form-inline">
	{% csrf_token %}
<input type="hidden" name="questCount" value="{{q.questCount}}" />
<input type="hidden" name="assessCode" value="{{assessCode}}" />
{%if branch%}
<input type="hidden" name="branchId" value="{{branch.id}}" />
{%endif%}
<input type="hidden" name="assessorId" value="{{assessor.id|default:''}}" />
<div style="float:left;width:40%">
<img src="/go_static/img/title.png" width="100%"></img>
</div>
<div style="float:right;width:40%;text-align:right;line-height:30px;">{{login_teacher.branchId}}{{branch.branchName}}校区</div>
<div style="clear:both;text-align:center;padding:20px 0 16px 0;">
<h3>{{q.title}}</h3>
</div>


<div style="font-size:16px;margin-bottom:20px;">
  {{q.prelude}}
</div>

<div style="width:100%;margin:0 auto;padding:0 0 20px 0;">





<div><center><h5>共{{q.questCount}}个问题</h5></center></div>
{%for q in qs%}
<div>
  <h5>{{q.sn}}.{{q.q}}</h5>
  {%if q.fill == 1%}
    <input type="text" id="{{q.sn}}" name="{{q.sn}}" style="width:{%if q.len%}{{q.len}}px{%else%}100%{%endif%}" />{{q.post|default:''}}
	{%elif q.list == 1%}
	  <select id="{{q.sn}}" name="{{q.sn}}">
			<option value="">请选择</option>
			{%for an in q.ans%}
			<option value="{{an.code}}">{{an.text}}</option>
			{%endfor%}
		</select>
  {%else%}
    {%for an in q.ans%}
      <div class="radio"><label>
      <input type="{%if q.multi == 1%}checkbox{%else%}radio{%endif%}" id="{{q.sn}}" name="{{q.sn}}" value="{{an.code}}" />{{an.code}}.{{an.text}}
      </label></div>
    {%endfor%}
	{%endif%}
</div>
{%endfor%}
<div style="padding:30px 0 10px 0;">
<center><input type="submit" value="提交" class="btn btn-success" style="width:90%" /></center>
</div>
</form>
{% endblock %}
{% block scripts %}
<script>
$("title").html('真朴围棋调查问卷')

$('#qform').validate({
    rules: {
			{%for q in qs%}
			  //if q.fill != 1%}
        {{q.sn}}: {
            required: true
        },
				//endif%}
			{%endfor%}
			{%if not branch%}
			branchId:{
					required: true
			},
			{%endif%}

    }
});
function gotBranch(){
	var branchId = $("#branchId").val()
	var url = 'q?tag=201908_'+branchId
	location.href=url
}
</script>
{% endblock %}

teacher/templates/q2019Done.html
{% extends "base.html" %}
{% block content %}
<div style="font-size:20px;">
<img src="/go_static/img/logo.png" width="30" />真朴儿童围棋教室
</div>
<center>
	<div style="padding-top:20px;">
<h4>问卷已提交，感谢您的参与！</h4>
</div>
</center>
{% endblock %}
{% block scripts %}
<script>


</script>
{% endblock %}

teacher/templates/questionnaireDone.html
{% extends "base.html" %}
{% block content %}
<div style="font-size:20px;">
<img src="/go_static/img/logo.png" width="30" />真朴儿童围棋教室
</div>
<center>
	<div style="padding-top:20px;">
<h4>满意度问卷已提交，感谢您的参与！</h4>
</div>

{%if sid%}
<div style="padding:20px;">
去看看{{sname|default:""}}小朋友的真朴学习档案吧
</div>
<div class="btn btn-success" style="padding:10px;">
	<a href="http://go2crm.cn/go2/student/achievement?studentId={{sid}}"><span style="color:white;">查看学习档案</span></a>
</div>
{%endif%}

</center>
{% endblock %}
{% block scripts %}
<script>


</script>
{% endblock %}

teacher/templates/wxqrcodePic.html
{% extends "base.html" %}

{% block styles %}
    <style>

    </style>
{% endblock %}
{% block content %}

<div id="post" style="display:none;
background-image:url('/go_static/img/zp_post_201810_a.jpg');
background-repeat:no-repeat;
background-attachment:fixed;
background-size:413px 700px;
">
  <img id="postPic" style="position:fixed;left:300px;top:500px" src="{{qrcode}}" />
</div>

<div id="qrcodeDiv">
<div id="back" style="padding-top:10px;padding-bottom:3;">
<a href="/go2/teacher/teacherList"><返回</a>
</div>
<hr style="margin-top:2px;margin-bottom:10px"/>

<a href="p20181111?bid={{teacher.branch.id}}&tid={{tid}}"><button>查看2018双11海报</button></a>

<div style="padding:20px;">
<h4>{{teacher.name}} 微信二维码</h4>
<img src="{{qrcode}}?tag={{millis}}" width="100" />
</div>

<button onclick="showPost()">查看海报</button>
<p>
  <br>
</p>

<form method="post" enctype="multipart/form-data">
{% csrf_token %}
    {{ form }}
<br><br>
<input type="submit" value="上传微信二维码">
</form>
</div>
{% endblock %}
{% block scripts %}
<script>
$("#id_tid").val('{{tid}}');
function showPost(){
  var leftRatio = 0.71;
  var topRatio = 0.83;
  var wid = $(window).width()
  var picHei = wid * 3 / 2
  var top = picHei * topRatio
  var left = wid*leftRatio

  $(".container").css("padding","0")
  $(".container").css("margin","0")
  $(".container").css("width",$(window).width()+'px')
  $("#qrcodeDiv").css("display","none")
  $("#post").css("display","block")
  $("#post").css("background-size",wid+"px"+" "+picHei+"px")
  $("#postPic").attr("src","{{qrcode}}?tag="+new Date())
  $("#postPic").css("width",'100px')
  $("#postPic").css("left",left+'px')
  $("#postPic").css("top",top+'px')
  $("#post").css("width",wid+'px')
  $("#post").css("height",picHei+'px')

}
</script>
{% endblock %}