branch/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'bee'
from django.conf.urls import include, url
from branch.views import *
urlpatterns = [

    # reg
    url(r'^reg$', reg, name='reg'),
    url(r'^apiReg$', api_reg, name='api_reg'),
    url(r'^city$', city, name='city'),
    url(r'^apiCity$', api_city, name='api_city'),
    url(r'^branchList$', branch_list, name='branch_list'),
    url(r'^branchInfo/(?P<branch_oid>[\w]{24})/$', branch_info, name='branch_info'),
    url(r'^cityList$', city_list, name='city_list'),
    url(r'^branchPic$', branchPic,name='branchPic'),
    url(r'^statistics$', statistics,name='statistics'),
    url(r'^netUser$', netUser,name='netUser'),
    url(r'^editCategory$', editCategory,name='editCategory'),
    url(r'^editSource$', editSource,name='editSource'),
    url(r'^api_editCategory$', api_editCategory,name='api_editCategory'),
    url(r'^api_editSource$', api_editSource,name='api_editSource'),
    url(r'^sources$', sources,name='sources'),
    url(r'^reimburses$', reimburses,name='reimburses'),
    url(r'^reimburse$', reimburse,name='reimburse'),
    url(r'^reimburseShow$', reimburseShow,name='reimburseShow'),
    url(r'^reimburseErr$', reimburseErr,name='reimburseErr'),
    
    url(r'^reimburseRemove_api$', reimburseRemove_api,name='reimburseRemove_api'),
    url(r'^api_submitReimburse$', api_submitReimburse,name='api_submitReimburse'),
    url(r'^reimburseNum_api$', reimburseNum_api,name='reimburseNum_api'),
    
    url(r'^jointDate$', jointDate,name='jointDate'),
    url(r'^cityContract$', cityContract,name='cityContract'),
    url(r'^editContract$', editContract,name='editContract'),
    url(r'^api_editContract$', api_editContract,name='api_editContract'),
    url(r'^vocations$', vocations,name='vocations'),
    url(r'^api_delVocation$', api_delVocation,name='api_delVocation'),
    url(r'^api_vocation$', api_vocation,name='api_vocation'),
    url(r'^tweet2019$', tweet2019,name='tweet2019'),
    
]

go2/urls.py
from django.conf.urls import url
from django.contrib import admin
from regUser.views import student_list,dboard
from teacher.views import show_login ,logout, noright,questionnaire,api_questionnaire
from webpage.views import showPage,weixinTXT
from django.conf.urls import include
import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', dboard,name="dboard"),
    url(r'^MP_verify_khiOZqwCFngYL7Tg.txt$', weixinTXT,name="weixinTXT"),
    url(r'^go2/regUser/', include('regUser.urls', namespace="regUser")),
    url(r'^go2/branch/', include('branch.urls', namespace="branch")),
    url(r'^go2/contract/', include('contract.urls', namespace="contract")),
    url(r'^go2/teacher/', include('teacher.urls', namespace="teacher")),
    url(r'^go2/gradeClass/', include('gradeClass.urls', namespace="gradeClass")),
    url(r'^go2/statistic/', include('statistic.urls', namespace="statistic")),
    url(r'^go2/student/', include('student.urls', namespace="student")),
    url(r'^web/', include('webpage.urls', namespace="web")),
    url(r'^go2/workflow/', include('workflow.urls', namespace="workflow")),
    url(r'^go2/login/$', show_login,name="login"),
    url(r'^go2/logout/$', logout,name="logout"),
    url(r'^go2/noright/$', noright,name="noright"),
    url(r'^go2/q$', questionnaire,name="q"),
    url(r'^go2/api_questionnaire$', api_questionnaire,name="api_q"),
    url(r'^page/(?P<sn>[\w]{1,5})/$', showPage,name="showPage"),
    
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

regUser/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'patch'
from django.conf.urls import include, url
from regUser.views import *

urlpatterns = [

    # reg
    url(r'^reg$', reg,name='reg'),
    url(r'^netReg$',netReg,name='netReg'),
    url(r'^apiReg$', api_reg, name='api_reg'),
    url(r'^addSourceCategory$', addSourceCategory,name='addSourceCategory'),
    url(r'^addSource$', addSource,name='addSource'),
    # 学生列表
    url(r'^studentList$', student_list, name='student_list'),
    url(r'^studentInfo/(?P<student_oid>[\w]{24})/$', student_info, name='student_info'),
    url(r'^apiSaveDemo/(?P<demo_oid>[\w]{24})/$', api_save_demo, name='api_save_demo'),
    url(r'^saveUserRemind$', save_user_remind, name='save_user_remind'),
    url(r'^studentSaveDeposit$', student_save_deposit, name='student_save_deposit'),
    url(r'^studentDeposit$', student_deposit, name='student_deposit'),
    url(r'^getByOids$', getByOids,name='getByOids'),
    url(r'^sms$', sms,name='sms'),
    url(r'^SMSTemplateEdit$', smsTemplateEdit,name='smsTemplateEdit'),
    url(r'^saveSMSTemplate$', api_saveSMSTemplate,name='api_saveSMSTemplate'),
    url(r'^showSMSTemplates$', showSMSTemplates,name='showSMSTemplates'),
    url(r'^uploadPic$', uploadPic,name='uploadPic'),
    url(r'^removePic$', removePic,name='removePic'),
    url(r'^removeTrack$', removeTrack,name='removeTrack'),
    url(r'^removeDup$', removeDup,name='removeDup'),
    url(r'^resolve_api$', resolve_api,name='resolve_api'),
    url(r'^resolve0$', resolve0,name='resolve0'),
    url(r'^resolve0_api$', resolve0_api,name='resolve0_api'),
    url(r'^resolveToDo_api$', resolveToDo_api,name='resolveToDo_api'),
    url(r'^done$', done,name='done'),
    url(r'^rr$', rr,name='rr'),
    url(r'^rer$', rer,name='rer'),
    url(r'^excelUser$', excelUser,name='excelUser'),
    url(r'^userShare$', userShare,name='userShare'),
    url(r'^picMemo$', picMemo,name='picMemo'),
    url(r'^dboard1$', dboard1,name='dboard1'),
    url(r'^dboard2$', dboard2,name='dboard2'),
    url(r'^dboard3$', dboard3,name='dboard3'),
    url(r'^dboard4$', dboard4,name='dboard4'),
    url(r'^dboard5$', dboard5,name='dboard5'),
    url(r'^dboard6$', dboard6,name='dboard6'),
    url(r'^dboard9$', dboard9,name='dboard9'),
    url(r'^dboard10$', dboard10,name='dboard10'),
    url(r'^dboard11$', dboard11,name='dboard11'),
    url(r'^dboard12$', dboard12,name='dboard12'),
    url(r'^dboard13$', dboard13,name='dboard13'),
    url(r'^searchKid$', searchKid,name='searchKid'),
    url(r'^searchReferTeacher$', searchReferTeacher,name='searchReferTeacher'),
    url(r'^regFromWxProg$', regFromWxProg,name='regFromWxProg'),
    url(r'^fan$', fan,name='fan'),
    url(r'^referPages$', referPages,name='referPages'),
]

student/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'patch'
from django.conf.urls import include, url
from student.views import *
urlpatterns = [
    url(r'^achievement$', achievement,name='achievement'),  # @UndefinedVariable
    url(r'^students$', students,name='students'),  # @UndefinedVariable
    url(r'^studentMemo$', studentMemo,name='studentMemo'),  # @UndefinedVariable
    url(r'^api_studentMemo$', api_studentMemo,name='api_studentMemo'),  # @UndefinedVariable
    url(r'^api_memoDelete$', api_memoDelete,name='api_memoDelete'),  # @UndefinedVariable
    url(r'^api_end$', api_end,name='api_end'),  # @UndefinedVariable
    url(r'^habit$', habit,name='habit'),  # @UndefinedVariable
    url(r'^title$', title,name='title'),  # @UndefinedVariable
    url(r'^titleLogin$', titleLogin,name='titleLogin'),  # @UndefinedVariable
    url(r'^api_suspend$', api_suspend,name='api_suspend'),  # @UndefinedVariable
    url(r'^api_delSuspension$', api_delSuspension,name='api_delSuspension'),  # @UndefinedVariable
    url(r'^question$', question,name='question'),  # @UndefinedVariable
    url(r'^quests$',quests,name="quests"),
    url(r'^studentDo$',studentDo,name="studentDo"),
    url(r'^api_editTarget$', api_editTarget,name='api_editTarget'),  # @UndefinedVariable
    url(r'^api_saveRecord$', api_saveRecord,name='api_saveRecord'),  # @UndefinedVariable
    url(r'^tweet$',tweet,name="tweet"),
    url(r'^api_tweet$',api_tweet,name="api_tweet"),
]

teacher/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'bee'
from django.conf.urls import include, url
from teacher.views import *
urlpatterns = [

    # reg
    url(r'^reg$', reg, name='reg'),
    url(r'^apiReg$', api_reg, name='api_reg'),

    # 老师列表
    url(r'^teacherList$', teacher_list, name='teacher_list'),
    url(r'^trainings/(?P<teacher_oid>[\w]{24})/$', trainings, name='trainings'),
    url(r'^trainingEditForm$', trainingEditForm, name='trainingEditForm'),
    url(r'^trainingEdit$', trainingEdit, name='trainingEdit'),
    url(r'^changePw$', changePw, name='changePw'),
    url(r'^pwForm$', pwForm, name='pwForm'),
    url(r'^checkOpenId$',checkOpenId,name="checkOpenId"),
    url(r'^api_getMessage$',api_getMessage,name="api_getMessage"),
    url(r'^api_readMessage$',api_readMessage,name="api_readMessage"),
    url(r'^message$',message,name="message"),
    url(r'^api_sendMessage$',api_sendMessage,name="api_sendMessage"),
    url(r'^api_push$',api_push,name="api_push"),
    url(r'^teacherQrcode$',teacherQrcode,name="teacherQrcode"),
    url(r'^api_headmasterAssess$',api_headmasterAssess,name="api_headmasterAssess"),
    url(r'^headmasterAssess$',headmasterAssess,name="headmasterAssess"),
    url(r'^headmasterAssesses$',headmasterAssesses,name="headmasterAssesses"),
    url(r'^questionnaire$',questionnaire,name="questionnaire"),
    url(r'^api_questionnaire$',api_questionnaire,name="api_questionnaire"),
    url(r'^questionnaireResult$',questionnaireResult,name="questionnaireResult"),
    url(r'^teacherAvail$',teacherAvail,name="teacherAvail"),
    url(r'^markStep$',markStep,name="markStep"),
    url(r'^api_markStep$',api_markStep,name="api_markStep"),
    url(r'^wxqrcodePic$',wxqrcodePic,name="wxqrcodePic"),
    url(r'^p20181111$',p20181111,name="p20181111"),
    url(r'^cityTeacherSteps$',cityTeacherSteps,name="cityTeacherSteps"),
    url(r'^api_editTarget$', api_editTarget,name='api_editTarget'),  # @UndefinedVariable
    url(r'^teacherSteps$',teacherSteps,name="teacherSteps"),
    url(r'^api_resetTestPassword$',api_resetTestPassword,name="api_resetTestPassword"),
    url(r'^testUser$',testUser,name="testUser"),
    url(r'^q2019$',q2019,name="q2019"),
    url(r'^api_q2019$',api_q2019,name="api_q2019"),
    url(r'^q2019Result$',q2019Result,name="q2019Result"),
    
]

templates/assistTeacherModel.html
<!-- referrer Modal -->
<div class="modal fade" id="assistTeacherModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">助教老师</h4>
            </div>
            <div class="modal-body" id="info-body">
                <div class="panel panel-default">
                    <div class="panel-heading">请填写助教老师姓名或拼音&nbsp;&nbsp;
<input id="searchAssistName" name="searchAssistName" style="width:140px;" type="text"> <button id="doSearchAssistTeacher" type="button" class="btn btn-default" aria-label="search">
                         <span class="glyphicon glyphicon-search" aria-hidden="false"></span>在全部校区查询
                      </button>

                    </div>
                    <div class="panel-body">
                        <select id="assistTeachers" name="assistTeachers" size="16" style="width:400px"></select></div>
                    </div>

            </div>

        </div>
    </div>
</div>

templates/back.html
<div style="padding-top:10px;padding-bottom:3;">
<a href="javascript:history.go(-1)"><返回</a>
</div>
<hr style="margin-top:2px;margin-bottom:10px"/>

templates/base.html
{% load staticfiles %}
<html>
<head>

    <title>CRM</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <link rel="stylesheet" href="/go_static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/go_static/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/go_static/css/bootstrap3.4-icons.css">
    <link rel="stylesheet" href="/go_static/css/zhenpu.css?tag=1">
    <link rel="stylesheet" href="/go_static/media/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="/go_static/media/css/buttons.dataTables.min.css">

    <script src="/go_static/js/jquery2.min.js"></script>
    <script src="/go_static/js/bootstrap.min.js"></script>
    <script src="/go_static/js/jquery.validate.js"></script>
    <script src="/go_static/media/js/jquery.dataTables.min.js"></script>
   	<script type="text/javascript" language="javascript" src="/go_static/media/js/dataTables.buttons.min.js"></script>
	<script type="text/javascript" language="javascript" src="/go_static/media/js/buttons.html5.min.js"></script>
	<script type="text/javascript" language="javascript" src="/go_static/media/js/buttons.print.min.js"></script>

    <!--datetimepicker-->
    <link rel="stylesheet" type="text/css" href="/go_static/js/DateTimePicker/jquery.datetimepicker.css"/>
    <script src="/go_static/js/DateTimePicker/build/jquery.datetimepicker.full.min.js"></script>

    <script src="/go_static/js/utils.js?ver=20180302"></script>
    <script src="/go_static/js/config.js"></script>



</head>

<body>
<div class="container">
    {% block content %}内容{% endblock %}
</div>

{% block scripts %}

{% endblock %}
</body>
</html>

templates/include_reg.html
<div style="">
<!-- footer -->
<div style="background:#ffffff;text-align:center;border:1px solid #888888;border-radius:8px;box-shadow: 1px 1px 1px #888888;margin:20px;padding:20px;">
<h5 style="font-weight:600;color:rgb(255, 104, 39);">真朴儿童围棋教室</h5>
<div style="width:60%;margin:0 auto;padding-bottom:20px;">

</div>
<div class="footer_text">自然成长，自由发展；</div>
<div class="footer_text">成长围棋的倡导者和实践者。</div>
<div class="footer_text" style="padding:6px 0 0 0">学围棋的小朋友，</div>
<div class="footer_text">抗挫能力更强，</div>
<div class="footer_text">逻辑思维更严密</div>
<div class="footer_text">更自主、更自信、更专注</div>
<div class="footer_text" style="padding:6px 0 0 0">如果您的小朋友四岁了，想学围棋，</div>
<div class="footer_text">可直接点下面电话按钮拨打电话咨询:</div>
<div class="footer_text" style="padding:6px 0 16px 0;font-weight:600;"><a href="tel:{{page.branch.branchTel}}"><button  class="btn btn-success">{%if to and to.mobile%}{{to.mobile}}{%elif page.branch.branchTel%}{{page.branch.branchTel}}{%elif student.branch.branchTel%}{{student.branch.branchTel}}{%endif%}</button></a></div>
<div class="footer_text">或者填写孩子信息和您的联系方式：</div>
<form id="form1" method="post" action="{%url 'regUser:rer'%}">
<input type="hidden" name="branch" value="{{page.branch.id}}">
<input type="hidden" name="regBranch" value="{{student.branch.id}}">
<input type="hidden" name="referrer" value="{{student.id}}">
<input type="hidden" name="regTeacher" value="{%if student and student.teacher%}{{student.teacher.id|default:''}}{%elif to%}{{to.id}}{%endif%}">
<input type="hidden" name="sourceType" value="C">
<input id="teacher" type="hidden" name="teacher" value="{%if student and student.teacher%}{{student.teacher.id|default:''}}{%elif to%}{{to.id}}{%endif%}" />
<div style="padding-top:6px;padding-bottom:6px;"><input style="border-radius:3px;height:30px" type="text" name="name" id="name" placeholder="孩子名"></div>
<div style="padding-top:8px;padding-bottom:14px;"><input style="border-radius:3px;height:30px" type="text" id="prt1mobile" name="prt1mobile" placeholder="手机号"></div>
<div><span onclick="checkInput()" class="btn btn-success" style="width:80px;">提交</span></div>
</form>
<div class="footer_text">我们可以为您安排<font style="font-weight:600;color:rgb(255, 104, 39)">免费的体验课</font>哦</div>

</div>

<style>
.para{padding:10px;%}
.footer_text{
font-size:12px;
}
#grad1 {
    height: 3px;
    background: -webkit-linear-gradient(left, rgba(255,0,0,0), rgba(255,0,0,1)); /* Safari 5.1 - 6.0 */
    background: -o-linear-gradient(right, rgba(255,0,0,0), rgba(255,0,0,1)); /* Opera 11.1 - 12.0 */
    background: -moz-linear-gradient(right, rgba(255,0,0,0), rgba(255,0,0,1)); /* Firefox 3.6 - 15 */
    background: linear-gradient(to right, rgba(10,10,10,0), rgba(10,10,10,1)); /* 标准的语法（必须放在最后） */
}
#grad2 {
    height: 3px;
    background: -webkit-linear-gradient(right, rgba(255,0,0,0), rgba(255,0,0,1)); /* Safari 5.1 - 6.0 */
    background: -o-linear-gradient(left, rgba(255,0,0,0), rgba(255,0,0,1)); /* Opera 11.1 - 12.0 */
    background: -moz-linear-gradient(left, rgba(255,0,0,0), rgba(255,0,0,1)); /* Firefox 3.6 - 15 */
    background: linear-gradient(to left, rgba(10,10,10,0), rgba(10,10,10,1)); /* 标准的语法（必须放在最后） */
}
</style>

templates/logo.html
<style>
.badge1 {
   position:relative;
   border-radius:5px;
   border-width: 1px;
   background-color: #eeeeee;
}
.badge1[data-badge]:after {
   content:attr(data-badge);
   position:absolute;
   top:-1px;
   right:-12px;
   font-size:.7em;
   background:red;
   color:white;
   width:18px;height:18px;
   text-align:center;
   line-height:18px;
   border-radius:50%;
   box-shadow:0 0 1px #333;
}

.badge2 {
   position:relative;
   border-radius:5px;
   border-width: 1px;
   background-color: #555555;
}
.badge2[data-badge]:after {
   content:attr(data-badge);
   position:absolute;
   top:-1px;
   right:-12px;
   font-size:.7em;
   background:red;
   color:white;
   width:18px;height:18px;
   text-align:center;
   line-height:18px;
   border-radius:50%;
   box-shadow:0 0 1px #333;
}

.badge3 {
   position:relative;
   border-radius:5px;
   border-width: 1px;
   background-color: #ffffff;
}
.badge3[data-badge]:after {
   content:attr(data-badge);
   position:absolute;
   top:-1px;
   right:-12px;
   font-size:.7em;
   background:red;
   color:white;
   width:18px;height:18px;
   text-align:center;
   line-height:18px;
   border-radius:50%;
   box-shadow:0 0 1px #333;
}

</style>
<div align="left" style="float:left;width:50%">
  <img src="/go_static/img/logo.png" width="30" style="cursor:pointer;" onclick="window.location.href='/'"/>
  {{login_teacher.city}} <b>{{login_teacher.branchName}}</b>&nbsp;{{login_teacher.branchTel}}
</div>
<div align="right" style="float:left;width:50%">
  <button id="messageNum" class="badge1">消息</button>
  &nbsp;&nbsp;{{login_teacher.roleName}}-{{login_teacher.teacherName}}
  &nbsp;&nbsp;<a href='/go2/logout'>退出</a>
</div>
<script>
$("#messageNum").click(function(){
  window.location.href="/go2/teacher/message"
})
$.post("{% url 'teacher:api_getMessage'%}", {
}, function (res) {
    if (res.error == 0) {
        if(res.messageNum>0)
            $("#messageNum").attr("data-badge",res.messageNum)
    } else {
        alert("失败");
    }
});
</script>

templates/nav.html
    <div align="left" style="width:100%;clear:both;">
        {% if login_teacher.role == login_teacher.RoleAdm%}
          <a id="nav0" href="/">工作台</a> |
          <a id="nav6" href="{% url 'contract:contract_list' %}?branch={{login_teacher.branch}}">收入</a> |
        <a id="nav5" href="/go2/branch/branchList">校区</a> |
        <a id="nav4" href="/go2/teacher/teacherList">人员</a> |
        <a id="nav7" href="{%url 'statistic:indexStat'%}">统计</a> |
        {%elif login_teacher.role == login_teacher.RoleFin %}

        <a id="nav0" href="/">工作台</a> |
                <a id="nav1"  href="{% url 'regUser:student_list' %}">孩子&nbsp;</a>&nbsp;&nbsp; |
        <a id="nav6" href="{% url 'contract:contract_list' %}?branch={{login_teacher.branch}}">收入</a> |
        <a id="nav7" href="{%url 'statistic:indexStat'%}">统计</a> |
        <a id="nav4" href="/go2/teacher/teacherList">部门人员</a> |
        {%elif login_teacher.branchType == '1' and login_teacher.role < login_teacher.RoleFin %}
        <a id="nav0" href="/">工作台</a> |
        <a id="nav1"  class="badge3"  href="{% url 'regUser:student_list' %}">孩子&nbsp;</a>&nbsp;&nbsp; |
        <a id="nav6" href="{% url 'contract:contract_list' %}?branch={{login_teacher.branch}}">收入</a> |
        <a id="nav4" href="/go2/teacher/teacherList">部门人员</a> |
        <a id="nav5" href="/go2/branch/branchList">校区列表</a> |
        <a id="nav7" href="{%url 'statistic:indexStat'%}">统计</a> |
        {%elif login_teacher.branchType == '2'%}

          {%if login_teacher.showIncome == '1'%}
        <a id="nav0" href="/">工作台</a> |
        <a id="nav6" href="{% url 'contract:contract_list' %}?branch={{login_teacher.branch}}">收入</a> |
        <a id="nav7" href="{%url 'statistic:indexStat'%}">统计</a> |
          {%elif login_teacher.role == 5%}
          <a id="nav7" href="{%url 'statistic:indexStat'%}">统计</a> |
          {%endif%}
        <a id="nav4" href="/go2/teacher/teacherList">部门人员</a> |
        {%elif login_teacher.branchType == '0' %}
        <a id="nav0" href="/">工作台</a> |
        <a id="nav1"  class="badge3"  href="{% url 'regUser:student_list' %}">孩子&nbsp;</a>&nbsp;&nbsp; |
          {%if login_teacher.role > login_teacher.RoleTea%}
        <a id="nav6" href="{% url 'contract:contract_list' %}?branch={{login_teacher.branch}}">收入</a> |
          {%endif%}
        <a id="nav2" href="/go2/gradeClass/gradeClassList">班级</a> |
        <a id="nav9" href="{% url 'student:students' %}">学生</a> |
        <a id="nav3" href="/go2/gradeClass/schedule">日程</a> |
        <a id="nav5" href="/go2/branch/reg?branchId={{login_teacher.branch}}">校区</a> |

        <a id="nav4" href="/go2/teacher/teacherList">老师</a> |
        <a id="nav7" href="{%url 'statistic:indexStat'%}">统计</a> |
        {%elif login_teacher.branchType == '3' %}
        <a id="nav7" href="{%url 'statistic:indexStat'%}">统计</a> |
        <a id="nav5" href="/go2/branch/branchList">校区列表</a> |
        <a id="nav4" href="/go2/teacher/teacherList">部门人员</a> |

        {%endif%}
        
        <a id="nav10" class="badge3" href="{% url 'branch:reimburses'%}">报销&nbsp;</a>&nbsp;&nbsp; |
        <a id="nav8" href="/go_static/howto/index.html">帮助</a> |

        &nbsp;<button id="addKid" style="padding:4px 10px 4px 10px;background:yellow;" class="btn btn-default">添加孩子</button>

    </div>

<script>
$("#addKid").click(function(){
	{% if login_teacher.branchType == '1' and login_teacher.role < RoleAdm %}
	    if(mobileCheck()){
	    	window.location.href="{%url 'regUser:netReg'%}";
	    }
	    else{
	    	window.location.href="{%url 'regUser:reg'%}";
	    }
	{%else%}
	    window.location.href="{%url 'regUser:reg'%}";
	{%endif%}
	})

  {%if login_teacher.role == 7 or login_teacher.role == 9%}

  $.post("{% url 'branch:reimburseNum_api'%}", {
    "csrfmiddlewaretoken": "{{ csrf_token }}",
  }, function (res) {
      if (res.error == 0) {
          if(res.num>0)
              $("#nav10").attr("data-badge",res.num)
      } else {
          alert("失败");
      }
  });
  {%endif%}

  {%if login_teacher.role > 4%}

  $.post("{% url 'regUser:resolveToDo_api'%}", {
    "csrfmiddlewaretoken": "{{ csrf_token }}",
  }, function (res) {
      if (res.error == 0) {
          if(res.num>0)
              $("#nav1").attr("data-badge",res.num)
      } else {
          alert("失败");
      }
  });
  {%endif%}

</script>

templates/subNavJs.html
$("#subNav span").click(function(){
    $(this).append("<span style='background:white;color:red;'>查询中...</span>")
	var nav = $(this).attr("id");
	var less = 1;
	if(nav.length==8)less = 2;
	var a = nav.substring(nav.length-less,nav.length);
	var url = "{% url 'regUser:dboard1' %}";
	url = url.substring(0,url.length-1)+a;
	if(a=='8'){
	    url = "{% url 'regUser:reg' %}";
	}
  if(a=='14'){
	    url = "{% url 'web:regList' %}";
	}
  if(a=='15'){
	    url = "{% url 'contract:duePay' %}";
	}
  if(a=='20'){
	    url = "{% url 'workflow:refundApprovedList' %}";
	}
  if(a=='21'){
      url = "{% url 'workflow:refundWaitingList' %}";
  }
  if(a=='22'){
      url = "{% url 'workflow:receiptRequire' %}";
  }
  if(a=='23'){
      url = "{% url 'workflow:receipts' %}";
  }
  if(a=='25'){
      url = "{% url 'workflow:reimburseApps' %}?hasReceipt=1";
  }
  if(a=='26'){
      url = "{% url 'workflow:reimburseApps' %}?hasReceipt=0";
  }
  if(a=='27'){
      url = "{% url 'workflow:reimburseDeals' %}?hasReceipt=1";
  }
  if(a=='28'){
      url = "{% url 'workflow:reimburseDeals' %}?hasReceipt=0";
  }
  if(a=='30'){
      url = "{% url 'contract:AllduePay' %}";
  }
	if(a==99){
	   alert('功能即将完成，敬请期待');
	   return;
	}
	window.location.href=url;
});